{
//=========Macro generated from canvas: Bin_5_NEvent_Spread/Bin_5_NEvent_Spread
//=========  (Sat Apr  4 19:05:57 2020) by ROOT version5.34/34
   TCanvas *Bin_5_NEvent_Spread = new TCanvas("Bin_5_NEvent_Spread", "Bin_5_NEvent_Spread",0,22,700,500);
   gStyle->SetOptStat(0);
   Bin_5_NEvent_Spread->SetHighLightColor(2);
   Bin_5_NEvent_Spread->Range(39.64803,-11.6875,56.19803,105.1875);
   Bin_5_NEvent_Spread->SetFillColor(0);
   Bin_5_NEvent_Spread->SetBorderMode(0);
   Bin_5_NEvent_Spread->SetBorderSize(2);
   Bin_5_NEvent_Spread->SetFrameBorderMode(0);
   Bin_5_NEvent_Spread->SetFrameBorderMode(0);
   
   TH1F *Bin_5_NEvent_Spread_Hist__2 = new TH1F("Bin_5_NEvent_Spread_Hist__2","Bin 5 (FGD1 numuCC 0pi, {p_{#mu}, cos#theta_{#mu}} = {650-700, -1-0.6})",1000,0,143.913);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(293,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(303,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(304,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(306,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(307,3);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(308,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(309,5);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(310,7);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(311,4);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(312,11);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(313,13);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(314,12);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(315,10);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(316,10);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(317,19);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(318,19);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(319,31);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(320,37);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(321,42);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(322,42);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(323,38);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(324,47);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(325,63);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(326,72);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(327,54);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(328,66);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(329,68);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(330,80);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(331,85);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(332,85);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(333,76);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(334,85);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(335,75);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(336,81);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(337,57);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(338,69);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(339,74);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(340,67);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(341,55);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(342,59);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(343,52);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(344,52);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(345,44);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(346,38);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(347,39);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(348,25);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(349,19);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(350,25);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(351,18);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(352,16);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(353,10);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(354,12);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(355,6);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(356,3);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(357,2);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(358,2);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(359,2);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(360,3);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(361,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(362,2);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(364,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(367,1);
   Bin_5_NEvent_Spread_Hist__2->SetBinContent(374,1);
   Bin_5_NEvent_Spread_Hist__2->SetMinimum(0);
   Bin_5_NEvent_Spread_Hist__2->SetMaximum(93.5);
   Bin_5_NEvent_Spread_Hist__2->SetEntries(2000);
   Bin_5_NEvent_Spread_Hist__2->SetDirectory(0);
   Bin_5_NEvent_Spread_Hist__2->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Bin_5_NEvent_Spread_Hist__2->SetLineColor(ci);
   Bin_5_NEvent_Spread_Hist__2->SetLineWidth(2);
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetTitle("N_{Events}^{MC} selected");
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetRange(288,379);
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetLabelFont(42);
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetLabelSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetTitleSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetXaxis()->SetTitleFont(42);
   Bin_5_NEvent_Spread_Hist__2->GetYaxis()->SetTitle("N_{toys}");
   Bin_5_NEvent_Spread_Hist__2->GetYaxis()->SetLabelFont(42);
   Bin_5_NEvent_Spread_Hist__2->GetYaxis()->SetLabelSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetYaxis()->SetTitleSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetYaxis()->SetTitleFont(42);
   Bin_5_NEvent_Spread_Hist__2->GetZaxis()->SetLabelFont(42);
   Bin_5_NEvent_Spread_Hist__2->GetZaxis()->SetLabelSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetZaxis()->SetTitleSize(0.035);
   Bin_5_NEvent_Spread_Hist__2->GetZaxis()->SetTitleFont(42);
   Bin_5_NEvent_Spread_Hist__2->Draw("");
   
   TF1 *Bin_5_NEvent_Varying_Gaussian = new TF1("Bin_5_NEvent_Varying_Gaussian","Varying Gaussian",23.9855,95.942);
   Bin_5_NEvent_Varying_Gaussian->SetFillColor(19);
   Bin_5_NEvent_Varying_Gaussian->SetFillStyle(0);

   ci = TColor::GetColor("#ff0000");
   Bin_5_NEvent_Varying_Gaussian->SetLineColor(ci);
   Bin_5_NEvent_Varying_Gaussian->SetLineWidth(2);
   Bin_5_NEvent_Varying_Gaussian->SetChisquare(49.59779);
   Bin_5_NEvent_Varying_Gaussian->SetNDF(60);
   Bin_5_NEvent_Varying_Gaussian->GetXaxis()->SetLabelFont(42);
   Bin_5_NEvent_Varying_Gaussian->GetXaxis()->SetLabelOffset(0.015);
   Bin_5_NEvent_Varying_Gaussian->GetXaxis()->SetTitleSize(0.05);
   Bin_5_NEvent_Varying_Gaussian->GetXaxis()->SetTitleFont(42);
   Bin_5_NEvent_Varying_Gaussian->GetYaxis()->SetLabelFont(42);
   Bin_5_NEvent_Varying_Gaussian->GetYaxis()->SetLabelOffset(0.015);
   Bin_5_NEvent_Varying_Gaussian->GetYaxis()->SetTitleSize(0.05);
   Bin_5_NEvent_Varying_Gaussian->GetYaxis()->SetTitleOffset(1.1);
   Bin_5_NEvent_Varying_Gaussian->GetYaxis()->SetTitleFont(42);
   Bin_5_NEvent_Varying_Gaussian->SetParameter(0,80.97885);
   Bin_5_NEvent_Varying_Gaussian->SetParError(0,2.239658);
   Bin_5_NEvent_Varying_Gaussian->SetParLimits(0,0,0);
   Bin_5_NEvent_Varying_Gaussian->SetParameter(1,47.92878);
   Bin_5_NEvent_Varying_Gaussian->SetParError(1,0.03172593);
   Bin_5_NEvent_Varying_Gaussian->SetParLimits(1,0,0);
   Bin_5_NEvent_Varying_Gaussian->SetParameter(2,1.385669);
   Bin_5_NEvent_Varying_Gaussian->SetParError(2,0.02245865);
   Bin_5_NEvent_Varying_Gaussian->SetParLimits(2,0,0);
   Bin_5_NEvent_Varying_Gaussian->Draw("SAME");
   
   TF1 *Bin_5_NEvent_Total_Gaussian = new TF1("Bin_5_NEvent_Total_Gaussian","Total Gaussian",23.9855,95.942);
   Bin_5_NEvent_Total_Gaussian->SetFillColor(19);
   Bin_5_NEvent_Total_Gaussian->SetFillStyle(0);

   ci = TColor::GetColor("#00ff00");
   Bin_5_NEvent_Total_Gaussian->SetLineColor(ci);
   Bin_5_NEvent_Total_Gaussian->SetLineWidth(2);
   Bin_5_NEvent_Total_Gaussian->GetXaxis()->SetLabelFont(42);
   Bin_5_NEvent_Total_Gaussian->GetXaxis()->SetLabelOffset(0.015);
   Bin_5_NEvent_Total_Gaussian->GetXaxis()->SetTitleSize(0.05);
   Bin_5_NEvent_Total_Gaussian->GetXaxis()->SetTitleFont(42);
   Bin_5_NEvent_Total_Gaussian->GetYaxis()->SetLabelFont(42);
   Bin_5_NEvent_Total_Gaussian->GetYaxis()->SetLabelOffset(0.015);
   Bin_5_NEvent_Total_Gaussian->GetYaxis()->SetTitleSize(0.05);
   Bin_5_NEvent_Total_Gaussian->GetYaxis()->SetTitleOffset(1.1);
   Bin_5_NEvent_Total_Gaussian->GetYaxis()->SetTitleFont(42);
   Bin_5_NEvent_Total_Gaussian->SetParameter(0,80.97885);
   Bin_5_NEvent_Total_Gaussian->SetParError(0,0);
   Bin_5_NEvent_Total_Gaussian->SetParLimits(0,80.97885,80.97885);
   Bin_5_NEvent_Total_Gaussian->SetParameter(1,47.92525);
   Bin_5_NEvent_Total_Gaussian->SetParError(1,0);
   Bin_5_NEvent_Total_Gaussian->SetParLimits(1,47.92525,47.92525);
   Bin_5_NEvent_Total_Gaussian->SetParameter(2,1.987386);
   Bin_5_NEvent_Total_Gaussian->SetParError(2,0);
   Bin_5_NEvent_Total_Gaussian->SetParLimits(2,1.987386,1.987386);
   Bin_5_NEvent_Total_Gaussian->Draw("SAME");
   TLine *line = new TLine(47.971,0,47.971,93.5);
   line->SetLineStyle(2);
   line->SetLineWidth(2);
   line->Draw();
   
   TLegend *leg = new TLegend(0.65,0.65,0.98,0.94,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Bin_5_NEvent_Spread_Hist","Bin content from throws, #mu=47.9#pm1.4","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Bin_5_NEvent_Varying_Gaussian","Gaussian from thrown cov, #chi^{2}_{nbins}=0.0, #mu=47.9#pm1.4","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Bin_5_NEvent_Total_Gaussian","Gaussian from total cov, #mu=47.9#pm2.0","l");

   ci = TColor::GetColor("#00ff00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TLine","Nominal bin content, 48.0 events","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.15,0.9136441,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *text = pt->AddText("Bin 5 (FGD1 numuCC 0pi, {p_{#mu}, cos#theta_{#mu}} = {650-700, -1-0.6})");
   pt->Draw();
   Bin_5_NEvent_Spread->Modified();
   Bin_5_NEvent_Spread->cd();
   Bin_5_NEvent_Spread->SetSelected(Bin_5_NEvent_Spread);
}
