void cutBurnin() {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun

  //  gSystem->Load("$ROOTSYS/test/libEvent");

  //Get old file, old tree and set top branch address
  std::cout << "open up " << std::endl;
  TFile *oldfile = new TFile("14MayTH2D.root");
  //std::cout << "Got file " << std::endl;
  TTree *oldtree = (TTree*)oldfile->Get("posteriors");
  //std::cout << "Got trre " << std::endl;
  Long64_t nentries = oldtree->GetEntries();
  //  Event *event   = 0;
  int step;
  oldtree->SetBranchAddress("step",&step);

  //Create a new file + a clone of old tree in new file
  TFile *newfile = new TFile("14MayTH2DNoBurnin2.root","recreate");
  TTree *newtree = oldtree->CloneTree(0);

  for (Long64_t i=0;i<nentries; i++) {
    oldtree->GetEntry(i);
    if (step > 200000) newtree->Fill();
    //    event->Clear();
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}
